version: '3'

dotenv: ['.env']

tasks:
  print-env:
    desc: Print WEB_SERVER_IP environment variable
    cmds:
      - 'echo "WEB_SERVER_IP: $WEB_SERVER_IP"'

  kamal-setup:
    desc: Setup Kamal for the first time
    cmds:
      - kamal setup

  kamal-deploy:
    desc: Deploy application using Kamal
    cmds:
      - kamal deploy

  kamal-proxy-reboot:
    desc: Reboot and upgrade kamal-proxy on the server
    cmds:
      - kamal proxy reboot

  create-release:
    desc: Create and push a GitHub release
    cmds:
      - |
        # Get current version or generate one
        VERSION=$(date +"%Y.%m.%d-%H%M%S")
        echo "Creating release version: v$VERSION"
        
        # Create git tag
        git tag "v$VERSION"
        git push origin "v$VERSION"
        
        # Create GitHub release
        gh release create "v$VERSION" \
          --title "Release v$VERSION" \
          --notes "Automated release created on $(date)" \
          --latest

  create-secrets:
    desc: Create GitHub secrets from .env file
    cmds:
      - |
        export GITHUB_REPO="muthuishere/firebase-jwt-generator"
        export GITHUB_ENVIRONMENT="dev"
        go run secrets.go .env

  dev:
    desc: Run development server
    cmds:
      - |
        npm install -g serve
        serve public/ -p 4500